# 数据集配置
DATASET:
    DATA_DIR: "/home/aistudio/data/dataset"
    NUM_CLASSES: 7 
    TRAIN_FILE_LIST: "/home/aistudio/data/dataset/train_list.txt"
    VAL_FILE_LIST: "/home/aistudio/data/dataset/val_list.txt"
    TEST_FILE_LIST: "/home/aistudio/data/dataset/testA_list.txt"
    VIS_FILE_LIST: None
    # VIS_FILE_LIST: "/home/aistudio/work/dataset/testA_list.txt"


# 预训练模型配置
MODEL:
    MODEL_NAME: "unet"
    DEFAULT_NORM_TYPE: "bn"

# 其他配置
TRAIN_CROP_SIZE: (256, 256)
EVAL_CROP_SIZE: (256, 256)
AUG:
    AUG_METHOD: "unpadding"
    FIX_RESIZE_SIZE: (256, 256)
BATCH_SIZE: 32
TRAIN:
    PRETRAINED_MODEL_DIR: "./pretrained_model/unet_bn_coco/"
    MODEL_SAVE_DIR: "./saved_model/unet-weighted/"
    RESUME_MODEL_DIR: None
    SNAPSHOT_EPOCH: 1
TEST:
    TEST_MODEL: "./saved_model/unet-weighted/final"
SOLVER:
    NUM_EPOCHS: 1 # 1 for debug
    LR: 0.01
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    LR_WARMUP: True
    LR_WARMUP_STEPS: 2000
    DECAY_EPOCH: [12,16]
    LOSS: ["softmax_loss"]
    # LOSS: ["lovasz_softmax_loss","softmax_loss"]
    # LOSS_WEIGHT:
    #     LOVASZ_SOFTMAX_LOSS: 0.2
    #     SOFTMAX_LOSS: 0.8
    CROSS_ENTROPY_WEIGHT: [1.0, 1.0, 1.0, 1.0, 3.0, 5.0, 1.0]